# Osho Agyeya
# oshoagyeya123@gmail.com
# 7800191911
# VIT University Chennai Campus - 15BCE1326
# Resume has been posted in the Github repository
# innovaccer data analyst solution

## Removing exactly similar rows using pandas built in features:  duplicated and drop

In [1]:
import pandas as pd
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
import csv
import os
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("Deduplication Problem - Sample Dataset.csv")
df  #viewing data

                ln       dob gn            fn
0         SMITH JR  01/03/68  F       WILLIAM
1     ROTHMEYER JR  01/03/68  F       WILLIAM
2          ASBY JR  01/03/68  F       WILLIAM
3        SALTER JR  01/03/68  F       WILLIAM
4        SALTER JR  01/03/68  F       WILLIAM
5         BLAND JR  21/02/62  F       WILLIAM
6         BLAND JR  21/02/62  F       WILLIAM
7         BLAND JR  21/02/62  F       WILLIAM
8       SHAFFER JR  21/02/62  F       WILLIAM
9       SHAFFER JR  21/02/62  F       WILLIAM
10       BLAND III  21/02/62  F       WILLIAM
11        BLAND JR  21/02/62  F          BILL
12           BLAND  21/02/62  F       WILLIAM
13        BLAND JR  21/02/62  F       WILLIAM
14        BLAND JR  08/06/54  F       WILLIAM
15        BLAND JR  08/06/54  F       WILLIAM
16        BLAND JR  25/10/53  F       WILLIAM
17        BLAND JR  25/10/53  F       WILLIAM
18      SHAFFER JR  25/10/53  F       WILLIAM
19       DUNCAN JR  25/10/53  F        THOMAS
20      CARLSON JR  25/10/53  F           ROY
21      CARLSON JR  25/10/53  F           RON
22       DUNCAN JR  25/10/53  F           ROY
23      MICHAELSON  25/10/53  M           ROY
24   MICHAELSON JR  25/10/53  M           ROY
25      MICHAELSON  25/10/53  M           ROY
26   MICHAELSON JR  25/10/53  M           ROY
27   MICHAELSON JR  01/05/51  M           ROY
28   MICHAELSON JR  17/06/48  M           ROY
29   MICHAELSON JR  17/06/48  M           ROY
30   MICHAELSON JR  09/04/47  M           ROY
31   MICHAELSON JR  09/04/47  M        ROBERT
32   MICHAELSON JR  09/04/47  M           BOB
33     MUSTAPHA JR  11/03/47  M          OWEN
34     MUSTAPHA JR  11/03/47  M          OWAN
35     HOUGHTON JR  31/01/46  M      LAWRENCE
36     HOUGHTON JR  31/01/46  M      LAWRENCE
37     HOUGHTON JR  31/01/46  M      LAWRENCE
38         LIND JR  31/01/46  M      LAWRENCE
39         LIND JR  31/01/46  M      LAWRENCE
40         LIND JR  31/01/46  M       KENNETH
41         LIND JR  31/01/46  M       KENNETH
42         LIND JR  20/01/46  M          JOHN
43         CAIN JR  20/01/46  M          JOHN
44           CLARK  09/06/45  M          JOHN
45           CLARK  09/02/45  M        RONALD
46           CLARK  09/02/45  M        DONALD
47           CLARK  16/12/44  M          JOHN
48        CLARK JR  16/12/44  M          JOHN
49        CLARK JR  16/12/44  M          JOHN
50   MICHAELSON JR  16/12/44  M          JOHN
51   MICHAELSON JR  16/12/44  M          JOHN
52   MICHAELSON JR  16/12/44  M          JOHN
53   MICHAELSON JR  24/04/40  M          JOHN
54   MICHAELSON JR  24/04/40  M          JOHN
55   MICHAELSON JR  24/06/39  M          JOHN
56   MICHAELSON JR  24/06/39  M          JOHN
57   MICHAELSON JR  24/06/39  M          JOHN
58   MICHAELSON JR  24/06/39  M         JAMES
59   MICHAELSON JR  24/06/39  M         JAMES
60   MICHAELSON JR  24/06/39  M          JACK
61   MICHAELSON JR  09/06/39  M          JACK
62       LARSON JR  09/06/39  M        HAROLD
63       LARSON JR  09/06/39  M        HAROLD
64     MUSTAPHA JR  07/10/37  M        HAROLD
65     HOUGHTON JR  07/10/37  M        HAROLD
66       MELVIN JR  07/10/37  M        HAROLD
67       MELVIN JR  07/10/37  M        HAROLD
68       MELVIN JR  07/10/37  M        HAROLD
69       MELVIN JR  07/10/37  M        HAROLD
70       MELVIN JR  07/10/37  M        HAROLD
71       MELVIN JR  07/10/37  M        HAROLD
72       MELVIN JR  07/10/37  M        HAROLD
73       MELVIN JR  07/10/37  M        HAROLD
74       MELVIN JR  07/10/37  M        HAROLD
75       CHAVAS JR  07/10/37  M        HAROLD
76       CHAVAS JR  07/10/37  M        HAROLD
77       CHAVAS JR  07/10/37  M        HAROLD
78       CHAVAS JR  07/10/37  M        HAROLD
79   MICHAELSON JR  07/10/37  M        HAROLD
80   MICHAELSON JR  07/10/37  M        HAROLD
81        SMITH JR  07/10/37  M        HAROLD
82       CHAVAS JR  07/10/37  M        HAROLD
83       CHAVAS JR  07/10/37  M        HAROLD
84        FAGEN JR  07/10/37  M        HAROLD
85        FAGEN JR  07/10/37  M        HAROLD
86        FAGEN JR  07/10/37  M        GEORGE
87      GRIFFIN JR  07/10/37  M          DARH
88      GRIFFIN JR  10/07/37  M          DARL
89      GRIFFIN JR  07/05/37  M          DARL
90      GRIFFIN JR  07/05/37  M      CLIFFORD
91      GRIFFIN JR  07/05/37  M      CLIFFORD
92      GRIFFIN JR  07/05/37  M      CLIFFORD
93      GRIFFIN JR  07/05/37  M      CLARENCE
94           HANNA  24/11/34  M     ADDISON J
95           HANNA  24/11/34  M  ADDISON JOHN
96           HANNA  24/11/34  M       ADDISON
97           HANNA  24/11/34  M       ADDISON
98           HANNA  24/11/34  M       ADDISON
99     GALETICH JR  15/10/32  M       ADDISON
100   FUNARO JONES  06/12/37  F       HARRIET
101       FUNARO J  06/12/37  F       HARRIET
102         FUNARO  06/12/37  F       HARRIET

In [3]:
df.duplicated() #locating duplicated rows

0      False
1      False
2      False
3      False
4       True
5      False
6       True
7       True
8      False
9       True
10     False
11     False
12     False
13      True
14     False
15      True
16     False
17      True
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25      True
26      True
27     False
28     False
29      True
30     False
31     False
32     False
33     False
34     False
35     False
36      True
37      True
38     False
39      True
40     False
41      True
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49      True
50     False
51      True
52      True
53     False
54      True
55     False
56      True
57      True
58     False
59      True
60     False
61     False
62     False
63      True
64     False
65     False
66     False
67      True
68      True
69      True
70      True
71      True
72      True
73      True
74      True
75     False
76      True
77      True
78      True
79     False
80      True
81     False
82      True
83      True
84     False
85      True
86     False
87     False
88     False
89     False
90     False
91      True
92      True
93     False
94     False
95     False
96     False
97      True
98      True
99     False
100    False
101    False
102    False
dtype: bool

In [4]:
df.loc[df.duplicated(),:] #seeing duplicated rows

               ln       dob gn        fn
4       SALTER JR  01/03/68  F   WILLIAM
6        BLAND JR  21/02/62  F   WILLIAM
7        BLAND JR  21/02/62  F   WILLIAM
9      SHAFFER JR  21/02/62  F   WILLIAM
13       BLAND JR  21/02/62  F   WILLIAM
15       BLAND JR  08/06/54  F   WILLIAM
17       BLAND JR  25/10/53  F   WILLIAM
25     MICHAELSON  25/10/53  M       ROY
26  MICHAELSON JR  25/10/53  M       ROY
29  MICHAELSON JR  17/06/48  M       ROY
36    HOUGHTON JR  31/01/46  M  LAWRENCE
37    HOUGHTON JR  31/01/46  M  LAWRENCE
39        LIND JR  31/01/46  M  LAWRENCE
41        LIND JR  31/01/46  M   KENNETH
49       CLARK JR  16/12/44  M      JOHN
51  MICHAELSON JR  16/12/44  M      JOHN
52  MICHAELSON JR  16/12/44  M      JOHN
54  MICHAELSON JR  24/04/40  M      JOHN
56  MICHAELSON JR  24/06/39  M      JOHN
57  MICHAELSON JR  24/06/39  M      JOHN
59  MICHAELSON JR  24/06/39  M     JAMES
63      LARSON JR  09/06/39  M    HAROLD
67      MELVIN JR  07/10/37  M    HAROLD
68      MELVIN JR  07/10/37  M    HAROLD
69      MELVIN JR  07/10/37  M    HAROLD
70      MELVIN JR  07/10/37  M    HAROLD
71      MELVIN JR  07/10/37  M    HAROLD
72      MELVIN JR  07/10/37  M    HAROLD
73      MELVIN JR  07/10/37  M    HAROLD
74      MELVIN JR  07/10/37  M    HAROLD
76      CHAVAS JR  07/10/37  M    HAROLD
77      CHAVAS JR  07/10/37  M    HAROLD
78      CHAVAS JR  07/10/37  M    HAROLD
80  MICHAELSON JR  07/10/37  M    HAROLD
82      CHAVAS JR  07/10/37  M    HAROLD
83      CHAVAS JR  07/10/37  M    HAROLD
85       FAGEN JR  07/10/37  M    HAROLD
91     GRIFFIN JR  07/05/37  M  CLIFFORD
92     GRIFFIN JR  07/05/37  M  CLIFFORD
97          HANNA  24/11/34  M   ADDISON
98          HANNA  24/11/34  M   ADDISON

In [5]:
df.to_pickle('before_delete.pkl')
df=pd.read_pickle('before_delete.pkl')  #saving and reloading
df

                ln       dob gn            fn
0         SMITH JR  01/03/68  F       WILLIAM
1     ROTHMEYER JR  01/03/68  F       WILLIAM
2          ASBY JR  01/03/68  F       WILLIAM
3        SALTER JR  01/03/68  F       WILLIAM
4        SALTER JR  01/03/68  F       WILLIAM
5         BLAND JR  21/02/62  F       WILLIAM
6         BLAND JR  21/02/62  F       WILLIAM
7         BLAND JR  21/02/62  F       WILLIAM
8       SHAFFER JR  21/02/62  F       WILLIAM
9       SHAFFER JR  21/02/62  F       WILLIAM
10       BLAND III  21/02/62  F       WILLIAM
11        BLAND JR  21/02/62  F          BILL
12           BLAND  21/02/62  F       WILLIAM
13        BLAND JR  21/02/62  F       WILLIAM
14        BLAND JR  08/06/54  F       WILLIAM
15        BLAND JR  08/06/54  F       WILLIAM
16        BLAND JR  25/10/53  F       WILLIAM
17        BLAND JR  25/10/53  F       WILLIAM
18      SHAFFER JR  25/10/53  F       WILLIAM
19       DUNCAN JR  25/10/53  F        THOMAS
20      CARLSON JR  25/10/53  F           ROY
21      CARLSON JR  25/10/53  F           RON
22       DUNCAN JR  25/10/53  F           ROY
23      MICHAELSON  25/10/53  M           ROY
24   MICHAELSON JR  25/10/53  M           ROY
25      MICHAELSON  25/10/53  M           ROY
26   MICHAELSON JR  25/10/53  M           ROY
27   MICHAELSON JR  01/05/51  M           ROY
28   MICHAELSON JR  17/06/48  M           ROY
29   MICHAELSON JR  17/06/48  M           ROY
30   MICHAELSON JR  09/04/47  M           ROY
31   MICHAELSON JR  09/04/47  M        ROBERT
32   MICHAELSON JR  09/04/47  M           BOB
33     MUSTAPHA JR  11/03/47  M          OWEN
34     MUSTAPHA JR  11/03/47  M          OWAN
35     HOUGHTON JR  31/01/46  M      LAWRENCE
36     HOUGHTON JR  31/01/46  M      LAWRENCE
37     HOUGHTON JR  31/01/46  M      LAWRENCE
38         LIND JR  31/01/46  M      LAWRENCE
39         LIND JR  31/01/46  M      LAWRENCE
40         LIND JR  31/01/46  M       KENNETH
41         LIND JR  31/01/46  M       KENNETH
42         LIND JR  20/01/46  M          JOHN
43         CAIN JR  20/01/46  M          JOHN
44           CLARK  09/06/45  M          JOHN
45           CLARK  09/02/45  M        RONALD
46           CLARK  09/02/45  M        DONALD
47           CLARK  16/12/44  M          JOHN
48        CLARK JR  16/12/44  M          JOHN
49        CLARK JR  16/12/44  M          JOHN
50   MICHAELSON JR  16/12/44  M          JOHN
51   MICHAELSON JR  16/12/44  M          JOHN
52   MICHAELSON JR  16/12/44  M          JOHN
53   MICHAELSON JR  24/04/40  M          JOHN
54   MICHAELSON JR  24/04/40  M          JOHN
55   MICHAELSON JR  24/06/39  M          JOHN
56   MICHAELSON JR  24/06/39  M          JOHN
57   MICHAELSON JR  24/06/39  M          JOHN
58   MICHAELSON JR  24/06/39  M         JAMES
59   MICHAELSON JR  24/06/39  M         JAMES
60   MICHAELSON JR  24/06/39  M          JACK
61   MICHAELSON JR  09/06/39  M          JACK
62       LARSON JR  09/06/39  M        HAROLD
63       LARSON JR  09/06/39  M        HAROLD
64     MUSTAPHA JR  07/10/37  M        HAROLD
65     HOUGHTON JR  07/10/37  M        HAROLD
66       MELVIN JR  07/10/37  M        HAROLD
67       MELVIN JR  07/10/37  M        HAROLD
68       MELVIN JR  07/10/37  M        HAROLD
69       MELVIN JR  07/10/37  M        HAROLD
70       MELVIN JR  07/10/37  M        HAROLD
71       MELVIN JR  07/10/37  M        HAROLD
72       MELVIN JR  07/10/37  M        HAROLD
73       MELVIN JR  07/10/37  M        HAROLD
74       MELVIN JR  07/10/37  M        HAROLD
75       CHAVAS JR  07/10/37  M        HAROLD
76       CHAVAS JR  07/10/37  M        HAROLD
77       CHAVAS JR  07/10/37  M        HAROLD
78       CHAVAS JR  07/10/37  M        HAROLD
79   MICHAELSON JR  07/10/37  M        HAROLD
80   MICHAELSON JR  07/10/37  M        HAROLD
81        SMITH JR  07/10/37  M        HAROLD
82       CHAVAS JR  07/10/37  M        HAROLD
83       CHAVAS JR  07/10/37  M        HAROLD
84        FAGEN JR  07/10/37  M        HAROLD
85        FAGEN JR  07/10/37  M        HAROLD
86        FAGEN JR  07/10/37  M        GEORGE
87      GRIFFIN JR  07/10/37  M          DARH
88      GRIFFIN JR  10/07/37  M          DARL
89      GRIFFIN JR  07/05/37  M          DARL
90      GRIFFIN JR  07/05/37  M      CLIFFORD
91      GRIFFIN JR  07/05/37  M      CLIFFORD
92      GRIFFIN JR  07/05/37  M      CLIFFORD
93      GRIFFIN JR  07/05/37  M      CLARENCE
94           HANNA  24/11/34  M     ADDISON J
95           HANNA  24/11/34  M  ADDISON JOHN
96           HANNA  24/11/34  M       ADDISON
97           HANNA  24/11/34  M       ADDISON
98           HANNA  24/11/34  M       ADDISON
99     GALETICH JR  15/10/32  M       ADDISON
100   FUNARO JONES  06/12/37  F       HARRIET
101       FUNARO J  06/12/37  F       HARRIET
102         FUNARO  06/12/37  F       HARRIET

In [6]:
df=df.drop_duplicates(keep='first') #removing exactly similar rows
df

                ln       dob gn            fn
0         SMITH JR  01/03/68  F       WILLIAM
1     ROTHMEYER JR  01/03/68  F       WILLIAM
2          ASBY JR  01/03/68  F       WILLIAM
3        SALTER JR  01/03/68  F       WILLIAM
5         BLAND JR  21/02/62  F       WILLIAM
8       SHAFFER JR  21/02/62  F       WILLIAM
10       BLAND III  21/02/62  F       WILLIAM
11        BLAND JR  21/02/62  F          BILL
12           BLAND  21/02/62  F       WILLIAM
14        BLAND JR  08/06/54  F       WILLIAM
16        BLAND JR  25/10/53  F       WILLIAM
18      SHAFFER JR  25/10/53  F       WILLIAM
19       DUNCAN JR  25/10/53  F        THOMAS
20      CARLSON JR  25/10/53  F           ROY
21      CARLSON JR  25/10/53  F           RON
22       DUNCAN JR  25/10/53  F           ROY
23      MICHAELSON  25/10/53  M           ROY
24   MICHAELSON JR  25/10/53  M           ROY
27   MICHAELSON JR  01/05/51  M           ROY
28   MICHAELSON JR  17/06/48  M           ROY
30   MICHAELSON JR  09/04/47  M           ROY
31   MICHAELSON JR  09/04/47  M        ROBERT
32   MICHAELSON JR  09/04/47  M           BOB
33     MUSTAPHA JR  11/03/47  M          OWEN
34     MUSTAPHA JR  11/03/47  M          OWAN
35     HOUGHTON JR  31/01/46  M      LAWRENCE
38         LIND JR  31/01/46  M      LAWRENCE
40         LIND JR  31/01/46  M       KENNETH
42         LIND JR  20/01/46  M          JOHN
43         CAIN JR  20/01/46  M          JOHN
44           CLARK  09/06/45  M          JOHN
45           CLARK  09/02/45  M        RONALD
46           CLARK  09/02/45  M        DONALD
47           CLARK  16/12/44  M          JOHN
48        CLARK JR  16/12/44  M          JOHN
50   MICHAELSON JR  16/12/44  M          JOHN
53   MICHAELSON JR  24/04/40  M          JOHN
55   MICHAELSON JR  24/06/39  M          JOHN
58   MICHAELSON JR  24/06/39  M         JAMES
60   MICHAELSON JR  24/06/39  M          JACK
61   MICHAELSON JR  09/06/39  M          JACK
62       LARSON JR  09/06/39  M        HAROLD
64     MUSTAPHA JR  07/10/37  M        HAROLD
65     HOUGHTON JR  07/10/37  M        HAROLD
66       MELVIN JR  07/10/37  M        HAROLD
75       CHAVAS JR  07/10/37  M        HAROLD
79   MICHAELSON JR  07/10/37  M        HAROLD
81        SMITH JR  07/10/37  M        HAROLD
84        FAGEN JR  07/10/37  M        HAROLD
86        FAGEN JR  07/10/37  M        GEORGE
87      GRIFFIN JR  07/10/37  M          DARH
88      GRIFFIN JR  10/07/37  M          DARL
89      GRIFFIN JR  07/05/37  M          DARL
90      GRIFFIN JR  07/05/37  M      CLIFFORD
93      GRIFFIN JR  07/05/37  M      CLARENCE
94           HANNA  24/11/34  M     ADDISON J
95           HANNA  24/11/34  M  ADDISON JOHN
96           HANNA  24/11/34  M       ADDISON
99     GALETICH JR  15/10/32  M       ADDISON
100   FUNARO JONES  06/12/37  F       HARRIET
101       FUNARO J  06/12/37  F       HARRIET
102         FUNARO  06/12/37  F       HARRIET

## Now, adding full name column along with a keep column to identify which rows should be kept

In [7]:
df['full']=df['fn']+str(" ")+df['ln'] #creating full name column
df = df.sort_values(by=['dob', 'gn', 'full']) #sorting by columns
df.to_pickle('after_stage1.pkl')

In [8]:
df=pd.read_pickle('after_stage1.pkl')
df=df.reset_index(drop=True)
df["keep"]=True #this column will tell which rows should be kept
print(df)
print(df.shape)
#after removing exactly similar rows, we are having 62 named rows

               ln       dob gn            fn                  full  keep
0         ASBY JR  01/03/68  F       WILLIAM       WILLIAM ASBY JR  True
1    ROTHMEYER JR  01/03/68  F       WILLIAM  WILLIAM ROTHMEYER JR  True
2       SALTER JR  01/03/68  F       WILLIAM     WILLIAM SALTER JR  True
3        SMITH JR  01/03/68  F       WILLIAM      WILLIAM SMITH JR  True
4   MICHAELSON JR  01/05/51  M           ROY     ROY MICHAELSON JR  True
5          FUNARO  06/12/37  F       HARRIET        HARRIET FUNARO  True
6        FUNARO J  06/12/37  F       HARRIET      HARRIET FUNARO J  True
7    FUNARO JONES  06/12/37  F       HARRIET  HARRIET FUNARO JONES  True
8      GRIFFIN JR  07/05/37  M      CLARENCE   CLARENCE GRIFFIN JR  True
9      GRIFFIN JR  07/05/37  M      CLIFFORD   CLIFFORD GRIFFIN JR  True
10     GRIFFIN JR  07/05/37  M          DARL       DARL GRIFFIN JR  True
11     GRIFFIN JR  07/10/37  M          DARH       DARH GRIFFIN JR  True
12       FAGEN JR  07/10/37  M        GEORGE       GEORGE FAGEN JR  True
13      CHAVAS JR  07/10/37  M        HAROLD      HAROLD CHAVAS JR  True
14       FAGEN JR  07/10/37  M        HAROLD       HAROLD FAGEN JR  True
15    HOUGHTON JR  07/10/37  M        HAROLD    HAROLD HOUGHTON JR  True
16      MELVIN JR  07/10/37  M        HAROLD      HAROLD MELVIN JR  True
17  MICHAELSON JR  07/10/37  M        HAROLD  HAROLD MICHAELSON JR  True
18    MUSTAPHA JR  07/10/37  M        HAROLD    HAROLD MUSTAPHA JR  True
19       SMITH JR  07/10/37  M        HAROLD       HAROLD SMITH JR  True
20       BLAND JR  08/06/54  F       WILLIAM      WILLIAM BLAND JR  True
21          CLARK  09/02/45  M        DONALD          DONALD CLARK  True
22          CLARK  09/02/45  M        RONALD          RONALD CLARK  True
23  MICHAELSON JR  09/04/47  M           BOB     BOB MICHAELSON JR  True
24  MICHAELSON JR  09/04/47  M        ROBERT  ROBERT MICHAELSON JR  True
25  MICHAELSON JR  09/04/47  M           ROY     ROY MICHAELSON JR  True
26      LARSON JR  09/06/39  M        HAROLD      HAROLD LARSON JR  True
27  MICHAELSON JR  09/06/39  M          JACK    JACK MICHAELSON JR  True
28          CLARK  09/06/45  M          JOHN            JOHN CLARK  True
29     GRIFFIN JR  10/07/37  M          DARL       DARL GRIFFIN JR  True
30    MUSTAPHA JR  11/03/47  M          OWAN      OWAN MUSTAPHA JR  True
31    MUSTAPHA JR  11/03/47  M          OWEN      OWEN MUSTAPHA JR  True
32    GALETICH JR  15/10/32  M       ADDISON   ADDISON GALETICH JR  True
33          CLARK  16/12/44  M          JOHN            JOHN CLARK  True
34       CLARK JR  16/12/44  M          JOHN         JOHN CLARK JR  True
35  MICHAELSON JR  16/12/44  M          JOHN    JOHN MICHAELSON JR  True
36  MICHAELSON JR  17/06/48  M           ROY     ROY MICHAELSON JR  True
37        CAIN JR  20/01/46  M          JOHN          JOHN CAIN JR  True
38        LIND JR  20/01/46  M          JOHN          JOHN LIND JR  True
39       BLAND JR  21/02/62  F          BILL         BILL BLAND JR  True
40          BLAND  21/02/62  F       WILLIAM         WILLIAM BLAND  True
41      BLAND III  21/02/62  F       WILLIAM     WILLIAM BLAND III  True
42       BLAND JR  21/02/62  F       WILLIAM      WILLIAM BLAND JR  True
43     SHAFFER JR  21/02/62  F       WILLIAM    WILLIAM SHAFFER JR  True
44  MICHAELSON JR  24/04/40  M          JOHN    JOHN MICHAELSON JR  True
45  MICHAELSON JR  24/06/39  M          JACK    JACK MICHAELSON JR  True
46  MICHAELSON JR  24/06/39  M         JAMES   JAMES MICHAELSON JR  True
47  MICHAELSON JR  24/06/39  M          JOHN    JOHN MICHAELSON JR  True
48          HANNA  24/11/34  M       ADDISON         ADDISON HANNA  True
49          HANNA  24/11/34  M     ADDISON J       ADDISON J HANNA  True
50          HANNA  24/11/34  M  ADDISON JOHN    ADDISON JOHN HANNA  True
51     CARLSON JR  25/10/53  F           RON        RON CARLSON JR  True
52     CARLSON JR  25/10/53  F           ROY        ROY CARLSON JR  True
53      DUNCAN JR  25/10/53  F           ROY         ROY DUNCAN JR  True
54      DUNCAN JR  25/10/53  F        THOMAS      THOMAS DUNCAN JR  True
55       BLAND JR  25/10/53  F       WILLIAM      WILLIAM BLAND JR  True
56     SHAFFER JR  25/10/53  F       WILLIAM    WILLIAM SHAFFER JR  True
57     MICHAELSON  25/10/53  M           ROY        ROY MICHAELSON  True
58  MICHAELSON JR  25/10/53  M           ROY     ROY MICHAELSON JR  True
59        LIND JR  31/01/46  M       KENNETH       KENNETH LIND JR  True
60    HOUGHTON JR  31/01/46  M      LAWRENCE  LAWRENCE HOUGHTON JR  True
61        LIND JR  31/01/46  M      LAWRENCE      LAWRENCE LIND JR  True
(62, 6)

## Method 1:to generate list of names that are similar. This method has been adopted from 

https://community.dynamics.com/crm/b/mannygrewaldynamicscrm/archive/2017/08/26/dedupe-duplicates-using-fuzzy-proximity-search

## which uses fuzzy proximity search to find the names that are similar. Output is a csv file with each row having names of people which are similar. This was used to understand fuzzy search that has been explored later in method 2

In [9]:
def pros(df1):
    FULL_MATCHING_THRESHOLD = 80
    PARTIAL_MATCHING_THRESHOLD = 100
    SORT_MATCHING_THRESHOLD = 100
    TOKEN_MATCHING_THRESHOLD = 100
    MAX_MATCHES=4
    current_db_dataframe=df1
    
    def find_matches(matchThis):
        rows = current_db_dataframe['full'].values.tolist();
        rows.remove(matchThis)
        matches= process.extractBests(matchThis,rows,scorer=fuzz.ratio,score_cutoff=FULL_MATCHING_THRESHOLD,limit=MAX_MATCHES)
        if len(matches)==0:
            matches= process.extractBests(matchThis,rows,scorer=fuzz.partial_ratio,score_cutoff=PARTIAL_MATCHING_THRESHOLD,limit=MAX_MATCHES);
            if len(matches)==0:
                matches= process.extractBests(matchThis,rows,scorer=fuzz.token_set_ratio,score_cutoff=TOKEN_MATCHING_THRESHOLD,limit=MAX_MATCHES);
                if len(matches)==0:
                    matches= process.extractBests(matchThis,rows,scorer=fuzz.token_sort_ratio,score_cutoff=SORT_MATCHING_THRESHOLD,limit=MAX_MATCHES);
        return matches[0][0] if len(matches)>0 else None


    fn_find_matches = lambda x: find_matches(x)
    current_db_dataframe['Duplicate']=current_db_dataframe.applymap(fn_find_matches)
    current_db_dataframe.to_csv("using crm crafted method.csv", index=False) #saving results to external file
    current_db_dataframe.to_pickle('using crm crafted method.pkl')

In [10]:
#this helps to generate a results.csv which tells names and their potential duplicates using fuzzy/proximity search 
pros(df[["full"]])  # this produces an output where in the last column, all the names that are similar to the name in the first column are displayed

## Method 2 using all the methods given in fuzzy wuzzy explicitly

# Using token_set_ratio approach. Here, this approach has been chosen out of ratio, partial ratio and token_sort_ratio because comparison is done as follows:

t0 = [SORTED_INTERSECTION]<br>
t1 = [SORTED_INTERSECTION]+[SORTED_REST_OF_STRING1]<br>
t2 = [SORTED_INTERSECTION]+[SORTED_REST_OF_STRING2]

### The intuition here is that because the SORTED_INTERSECTION component is always exactly the same, the scores increase when (a) that makes up a larger percentage of the full string, and (b) the string remainders are more similar. This takes into account abbreviations, letters added at the end & letters added in between the names which change the spelling of the names but imply the same person. The similarity between full names should be >=90. Each entry in the dataframe is compared with every other entry after it.

#### References: 
https://marcobonzanini.com/2015/02/25/fuzzy-string-matching-in-python/

http://chairnerd.seatgeek.com/fuzzywuzzy-fuzzy-string-matching-in-python/

#### Here, for 1st approach, it is considered that different dates of birth and different genders mean different patients even for same full name. We iterate over each patient and find out how much similar the full names of the patients coming after him in the dataframe are provided gender and dob are same.

In [11]:
#assuming that different dates of birth and different genders mean different patients even for same full name
def tokenset(df):
    tot=len(df)
    for i,r in df.iterrows():
        dobm=r["dob"]
        gm=r["gn"]
        fnm=r["full"]
        if(r["keep"]!=False):
            for j in range(i+1,tot):
                rc=df.iloc[j]
                dobc=rc["dob"]
                gc=rc["gn"]
                fnc=rc["full"]
                if(dobm==dobc and gm==gc):
                    if(fuzz.token_set_ratio(fnm,fnc)>90):
                        df.set_value(j,"keep",False)
    df=df[df["keep"]==True]
    df=df.reset_index(drop=True)
    print(df)
    print(df.shape)
    df.to_pickle("using token sort by unique dob and gender.pkl")
    df=df.drop(["full","keep"],axis=1)
    df.to_csv("using token sort by unique dob and gender.csv", index=False)
    #we dropped from 62 rows to 51 rows
tokenset(df)

               ln       dob gn        fn                  full  keep
0         ASBY JR  01/03/68  F   WILLIAM       WILLIAM ASBY JR  True
1    ROTHMEYER JR  01/03/68  F   WILLIAM  WILLIAM ROTHMEYER JR  True
2       SALTER JR  01/03/68  F   WILLIAM     WILLIAM SALTER JR  True
3        SMITH JR  01/03/68  F   WILLIAM      WILLIAM SMITH JR  True
4   MICHAELSON JR  01/05/51  M       ROY     ROY MICHAELSON JR  True
5          FUNARO  06/12/37  F   HARRIET        HARRIET FUNARO  True
6      GRIFFIN JR  07/05/37  M  CLARENCE   CLARENCE GRIFFIN JR  True
7      GRIFFIN JR  07/05/37  M  CLIFFORD   CLIFFORD GRIFFIN JR  True
8      GRIFFIN JR  07/05/37  M      DARL       DARL GRIFFIN JR  True
9      GRIFFIN JR  07/10/37  M      DARH       DARH GRIFFIN JR  True
10       FAGEN JR  07/10/37  M    GEORGE       GEORGE FAGEN JR  True
11      CHAVAS JR  07/10/37  M    HAROLD      HAROLD CHAVAS JR  True
12       FAGEN JR  07/10/37  M    HAROLD       HAROLD FAGEN JR  True
13    HOUGHTON JR  07/10/37  M    HAROLD    HAROLD HOUGHTON JR  True
14      MELVIN JR  07/10/37  M    HAROLD      HAROLD MELVIN JR  True
15  MICHAELSON JR  07/10/37  M    HAROLD  HAROLD MICHAELSON JR  True
16    MUSTAPHA JR  07/10/37  M    HAROLD    HAROLD MUSTAPHA JR  True
17       SMITH JR  07/10/37  M    HAROLD       HAROLD SMITH JR  True
18       BLAND JR  08/06/54  F   WILLIAM      WILLIAM BLAND JR  True
19          CLARK  09/02/45  M    DONALD          DONALD CLARK  True
20  MICHAELSON JR  09/04/47  M       BOB     BOB MICHAELSON JR  True
21  MICHAELSON JR  09/04/47  M    ROBERT  ROBERT MICHAELSON JR  True
22  MICHAELSON JR  09/04/47  M       ROY     ROY MICHAELSON JR  True
23      LARSON JR  09/06/39  M    HAROLD      HAROLD LARSON JR  True
24  MICHAELSON JR  09/06/39  M      JACK    JACK MICHAELSON JR  True
25          CLARK  09/06/45  M      JOHN            JOHN CLARK  True
26     GRIFFIN JR  10/07/37  M      DARL       DARL GRIFFIN JR  True
27    MUSTAPHA JR  11/03/47  M      OWAN      OWAN MUSTAPHA JR  True
28    GALETICH JR  15/10/32  M   ADDISON   ADDISON GALETICH JR  True
29          CLARK  16/12/44  M      JOHN            JOHN CLARK  True
30  MICHAELSON JR  16/12/44  M      JOHN    JOHN MICHAELSON JR  True
31  MICHAELSON JR  17/06/48  M       ROY     ROY MICHAELSON JR  True
32        CAIN JR  20/01/46  M      JOHN          JOHN CAIN JR  True
33        LIND JR  20/01/46  M      JOHN          JOHN LIND JR  True
34       BLAND JR  21/02/62  F      BILL         BILL BLAND JR  True
35          BLAND  21/02/62  F   WILLIAM         WILLIAM BLAND  True
36     SHAFFER JR  21/02/62  F   WILLIAM    WILLIAM SHAFFER JR  True
37  MICHAELSON JR  24/04/40  M      JOHN    JOHN MICHAELSON JR  True
38  MICHAELSON JR  24/06/39  M      JACK    JACK MICHAELSON JR  True
39  MICHAELSON JR  24/06/39  M     JAMES   JAMES MICHAELSON JR  True
40  MICHAELSON JR  24/06/39  M      JOHN    JOHN MICHAELSON JR  True
41          HANNA  24/11/34  M   ADDISON         ADDISON HANNA  True
42     CARLSON JR  25/10/53  F       RON        RON CARLSON JR  True
43      DUNCAN JR  25/10/53  F       ROY         ROY DUNCAN JR  True
44      DUNCAN JR  25/10/53  F    THOMAS      THOMAS DUNCAN JR  True
45       BLAND JR  25/10/53  F   WILLIAM      WILLIAM BLAND JR  True
46     SHAFFER JR  25/10/53  F   WILLIAM    WILLIAM SHAFFER JR  True
47     MICHAELSON  25/10/53  M       ROY        ROY MICHAELSON  True
48        LIND JR  31/01/46  M   KENNETH       KENNETH LIND JR  True
49    HOUGHTON JR  31/01/46  M  LAWRENCE  LAWRENCE HOUGHTON JR  True
50        LIND JR  31/01/46  M  LAWRENCE      LAWRENCE LIND JR  True
(51, 6)

#### Here, for 2nd approach, it is considered that different genders mean different patients even for same full name,dob. We iterate over each patient and find out how much similar the full names of the patients coming after him in the dataframe are provided gender is same.

In [12]:
#assuming that only different genders mean different patients even for same full name,dob
def tokenset2(df):
    tot=len(df)
    for i,r in df.iterrows():
        dobm=r["dob"]
        gm=r["gn"]
        fnm=r["full"]
        if(r["keep"]!=False):
            for j in range(i+1,tot):
                rc=df.iloc[j]
                dobc=rc["dob"]
                gc=rc["gn"]
                fnc=rc["full"]
                if(gm==gc):
                    if(fuzz.token_set_ratio(fnm,fnc)>90):
                        df.set_value(j,"keep",False)
    df=df[df["keep"]==True]
    df=df.reset_index(drop=True)
    print(df)
    print(df.shape)
    df.to_pickle("using token sort by unique gender.pkl")
    df=df.drop(["full","keep"],axis=1)
    df.to_csv("using token sort by unique gender.csv", index=False)
    #we dropped from 62 rows to 39 rows
tokenset2(df)

               ln       dob gn        fn                  full  keep
0         ASBY JR  01/03/68  F   WILLIAM       WILLIAM ASBY JR  True
1    ROTHMEYER JR  01/03/68  F   WILLIAM  WILLIAM ROTHMEYER JR  True
2       SALTER JR  01/03/68  F   WILLIAM     WILLIAM SALTER JR  True
3        SMITH JR  01/03/68  F   WILLIAM      WILLIAM SMITH JR  True
4   MICHAELSON JR  01/05/51  M       ROY     ROY MICHAELSON JR  True
5          FUNARO  06/12/37  F   HARRIET        HARRIET FUNARO  True
6      GRIFFIN JR  07/05/37  M  CLARENCE   CLARENCE GRIFFIN JR  True
7      GRIFFIN JR  07/05/37  M  CLIFFORD   CLIFFORD GRIFFIN JR  True
8      GRIFFIN JR  07/05/37  M      DARL       DARL GRIFFIN JR  True
9        FAGEN JR  07/10/37  M    GEORGE       GEORGE FAGEN JR  True
10      CHAVAS JR  07/10/37  M    HAROLD      HAROLD CHAVAS JR  True
11       FAGEN JR  07/10/37  M    HAROLD       HAROLD FAGEN JR  True
12    HOUGHTON JR  07/10/37  M    HAROLD    HAROLD HOUGHTON JR  True
13      MELVIN JR  07/10/37  M    HAROLD      HAROLD MELVIN JR  True
14  MICHAELSON JR  07/10/37  M    HAROLD  HAROLD MICHAELSON JR  True
15    MUSTAPHA JR  07/10/37  M    HAROLD    HAROLD MUSTAPHA JR  True
16       SMITH JR  07/10/37  M    HAROLD       HAROLD SMITH JR  True
17       BLAND JR  08/06/54  F   WILLIAM      WILLIAM BLAND JR  True
18          CLARK  09/02/45  M    DONALD          DONALD CLARK  True
19  MICHAELSON JR  09/04/47  M       BOB     BOB MICHAELSON JR  True
20  MICHAELSON JR  09/04/47  M    ROBERT  ROBERT MICHAELSON JR  True
21      LARSON JR  09/06/39  M    HAROLD      HAROLD LARSON JR  True
22  MICHAELSON JR  09/06/39  M      JACK    JACK MICHAELSON JR  True
23          CLARK  09/06/45  M      JOHN            JOHN CLARK  True
24    MUSTAPHA JR  11/03/47  M      OWAN      OWAN MUSTAPHA JR  True
25    GALETICH JR  15/10/32  M   ADDISON   ADDISON GALETICH JR  True
26  MICHAELSON JR  16/12/44  M      JOHN    JOHN MICHAELSON JR  True
27        CAIN JR  20/01/46  M      JOHN          JOHN CAIN JR  True
28        LIND JR  20/01/46  M      JOHN          JOHN LIND JR  True
29       BLAND JR  21/02/62  F      BILL         BILL BLAND JR  True
30     SHAFFER JR  21/02/62  F   WILLIAM    WILLIAM SHAFFER JR  True
31  MICHAELSON JR  24/06/39  M     JAMES   JAMES MICHAELSON JR  True
32          HANNA  24/11/34  M   ADDISON         ADDISON HANNA  True
33     CARLSON JR  25/10/53  F       RON        RON CARLSON JR  True
34      DUNCAN JR  25/10/53  F       ROY         ROY DUNCAN JR  True
35      DUNCAN JR  25/10/53  F    THOMAS      THOMAS DUNCAN JR  True
36        LIND JR  31/01/46  M   KENNETH       KENNETH LIND JR  True
37    HOUGHTON JR  31/01/46  M  LAWRENCE  LAWRENCE HOUGHTON JR  True
38        LIND JR  31/01/46  M  LAWRENCE      LAWRENCE LIND JR  True
(39, 6)

#### Here, for 3rd approach, it is considered that different dob mean different patients even for same full name,gender. We iterate over each patient and find out how much similar the full names of the patients coming after him in the dataframe are provided dob is same.

In [13]:
#asssuming that different dob mean different patients even for same full name,gender
def tokenset3(df):
    tot=len(df)
    for i,r in df.iterrows():
        dobm=r["dob"]
        gm=r["gn"]
        fnm=r["full"]
        if(r["keep"]!=False):
            for j in range(i+1,tot):
                rc=df.iloc[j]
                dobc=rc["dob"]
                gc=rc["gn"]
                fnc=rc["full"]
                if(dobm==dobc):
                    if(fuzz.token_set_ratio(fnm,fnc)>90):
                        df.set_value(j,"keep",False)
    df=df[df["keep"]==True]
    df=df.reset_index(drop=True)
    print(df)
    print(df.shape)
    df.to_pickle("using token sort by unique dob.pkl")
    df=df.drop(["full","keep"],axis=1)
    df.to_csv("using token sort by unique dob.csv", index=False)
    #we dropped from 62 rows to 39 rows
tokenset3(df)

               ln       dob gn        fn                  full  keep
0         ASBY JR  01/03/68  F   WILLIAM       WILLIAM ASBY JR  True
1    ROTHMEYER JR  01/03/68  F   WILLIAM  WILLIAM ROTHMEYER JR  True
2       SALTER JR  01/03/68  F   WILLIAM     WILLIAM SALTER JR  True
3        SMITH JR  01/03/68  F   WILLIAM      WILLIAM SMITH JR  True
4   MICHAELSON JR  01/05/51  M       ROY     ROY MICHAELSON JR  True
5          FUNARO  06/12/37  F   HARRIET        HARRIET FUNARO  True
6      GRIFFIN JR  07/05/37  M  CLARENCE   CLARENCE GRIFFIN JR  True
7      GRIFFIN JR  07/05/37  M  CLIFFORD   CLIFFORD GRIFFIN JR  True
8      GRIFFIN JR  07/05/37  M      DARL       DARL GRIFFIN JR  True
9        FAGEN JR  07/10/37  M    GEORGE       GEORGE FAGEN JR  True
10      CHAVAS JR  07/10/37  M    HAROLD      HAROLD CHAVAS JR  True
11       FAGEN JR  07/10/37  M    HAROLD       HAROLD FAGEN JR  True
12    HOUGHTON JR  07/10/37  M    HAROLD    HAROLD HOUGHTON JR  True
13      MELVIN JR  07/10/37  M    HAROLD      HAROLD MELVIN JR  True
14  MICHAELSON JR  07/10/37  M    HAROLD  HAROLD MICHAELSON JR  True
15    MUSTAPHA JR  07/10/37  M    HAROLD    HAROLD MUSTAPHA JR  True
16       SMITH JR  07/10/37  M    HAROLD       HAROLD SMITH JR  True
17       BLAND JR  08/06/54  F   WILLIAM      WILLIAM BLAND JR  True
18          CLARK  09/02/45  M    DONALD          DONALD CLARK  True
19  MICHAELSON JR  09/04/47  M       BOB     BOB MICHAELSON JR  True
20  MICHAELSON JR  09/04/47  M    ROBERT  ROBERT MICHAELSON JR  True
21      LARSON JR  09/06/39  M    HAROLD      HAROLD LARSON JR  True
22  MICHAELSON JR  09/06/39  M      JACK    JACK MICHAELSON JR  True
23          CLARK  09/06/45  M      JOHN            JOHN CLARK  True
24    MUSTAPHA JR  11/03/47  M      OWAN      OWAN MUSTAPHA JR  True
25    GALETICH JR  15/10/32  M   ADDISON   ADDISON GALETICH JR  True
26  MICHAELSON JR  16/12/44  M      JOHN    JOHN MICHAELSON JR  True
27        CAIN JR  20/01/46  M      JOHN          JOHN CAIN JR  True
28        LIND JR  20/01/46  M      JOHN          JOHN LIND JR  True
29       BLAND JR  21/02/62  F      BILL         BILL BLAND JR  True
30     SHAFFER JR  21/02/62  F   WILLIAM    WILLIAM SHAFFER JR  True
31  MICHAELSON JR  24/06/39  M     JAMES   JAMES MICHAELSON JR  True
32          HANNA  24/11/34  M   ADDISON         ADDISON HANNA  True
33     CARLSON JR  25/10/53  F       RON        RON CARLSON JR  True
34      DUNCAN JR  25/10/53  F       ROY         ROY DUNCAN JR  True
35      DUNCAN JR  25/10/53  F    THOMAS      THOMAS DUNCAN JR  True
36        LIND JR  31/01/46  M   KENNETH       KENNETH LIND JR  True
37    HOUGHTON JR  31/01/46  M  LAWRENCE  LAWRENCE HOUGHTON JR  True
38        LIND JR  31/01/46  M  LAWRENCE      LAWRENCE LIND JR  True
(39, 6)

#### Here, for 4th approach, only full name is considered. We iterate over each patient and find out how much similar the full names of the patients coming after him in the dataframe are.

In [14]:
#only taking full name into consideration
def tokenset4(df):
    tot=len(df)
    for i,r in df.iterrows():
        dobm=r["dob"]
        gm=r["gn"]
        fnm=r["full"]
        if(r["keep"]!=False):
            for j in range(i+1,tot):
                rc=df.iloc[j]
                dobc=rc["dob"]
                gc=rc["gn"]
                fnc=rc["full"]
                if(fuzz.token_set_ratio(fnm,fnc)>90):
                    df.set_value(j,"keep",False)
    df=df[df["keep"]==True]
    df=df.reset_index(drop=True)
    print(df)
    print(df.shape)
    df.to_pickle("using token sort by only full name.pkl")
    df=df.drop(["full","keep"],axis=1)
    df.to_csv("using token sort by only full name.csv", index=False)
    #we dropped from 62 rows to 39 rows
    #this is the best that can be reached
tokenset4(df)

               ln       dob gn        fn                  full  keep
0         ASBY JR  01/03/68  F   WILLIAM       WILLIAM ASBY JR  True
1    ROTHMEYER JR  01/03/68  F   WILLIAM  WILLIAM ROTHMEYER JR  True
2       SALTER JR  01/03/68  F   WILLIAM     WILLIAM SALTER JR  True
3        SMITH JR  01/03/68  F   WILLIAM      WILLIAM SMITH JR  True
4   MICHAELSON JR  01/05/51  M       ROY     ROY MICHAELSON JR  True
5          FUNARO  06/12/37  F   HARRIET        HARRIET FUNARO  True
6      GRIFFIN JR  07/05/37  M  CLARENCE   CLARENCE GRIFFIN JR  True
7      GRIFFIN JR  07/05/37  M  CLIFFORD   CLIFFORD GRIFFIN JR  True
8      GRIFFIN JR  07/05/37  M      DARL       DARL GRIFFIN JR  True
9        FAGEN JR  07/10/37  M    GEORGE       GEORGE FAGEN JR  True
10      CHAVAS JR  07/10/37  M    HAROLD      HAROLD CHAVAS JR  True
11       FAGEN JR  07/10/37  M    HAROLD       HAROLD FAGEN JR  True
12    HOUGHTON JR  07/10/37  M    HAROLD    HAROLD HOUGHTON JR  True
13      MELVIN JR  07/10/37  M    HAROLD      HAROLD MELVIN JR  True
14  MICHAELSON JR  07/10/37  M    HAROLD  HAROLD MICHAELSON JR  True
15    MUSTAPHA JR  07/10/37  M    HAROLD    HAROLD MUSTAPHA JR  True
16       SMITH JR  07/10/37  M    HAROLD       HAROLD SMITH JR  True
17       BLAND JR  08/06/54  F   WILLIAM      WILLIAM BLAND JR  True
18          CLARK  09/02/45  M    DONALD          DONALD CLARK  True
19  MICHAELSON JR  09/04/47  M       BOB     BOB MICHAELSON JR  True
20  MICHAELSON JR  09/04/47  M    ROBERT  ROBERT MICHAELSON JR  True
21      LARSON JR  09/06/39  M    HAROLD      HAROLD LARSON JR  True
22  MICHAELSON JR  09/06/39  M      JACK    JACK MICHAELSON JR  True
23          CLARK  09/06/45  M      JOHN            JOHN CLARK  True
24    MUSTAPHA JR  11/03/47  M      OWAN      OWAN MUSTAPHA JR  True
25    GALETICH JR  15/10/32  M   ADDISON   ADDISON GALETICH JR  True
26  MICHAELSON JR  16/12/44  M      JOHN    JOHN MICHAELSON JR  True
27        CAIN JR  20/01/46  M      JOHN          JOHN CAIN JR  True
28        LIND JR  20/01/46  M      JOHN          JOHN LIND JR  True
29       BLAND JR  21/02/62  F      BILL         BILL BLAND JR  True
30     SHAFFER JR  21/02/62  F   WILLIAM    WILLIAM SHAFFER JR  True
31  MICHAELSON JR  24/06/39  M     JAMES   JAMES MICHAELSON JR  True
32          HANNA  24/11/34  M   ADDISON         ADDISON HANNA  True
33     CARLSON JR  25/10/53  F       RON        RON CARLSON JR  True
34      DUNCAN JR  25/10/53  F       ROY         ROY DUNCAN JR  True
35      DUNCAN JR  25/10/53  F    THOMAS      THOMAS DUNCAN JR  True
36        LIND JR  31/01/46  M   KENNETH       KENNETH LIND JR  True
37    HOUGHTON JR  31/01/46  M  LAWRENCE  LAWRENCE HOUGHTON JR  True
38        LIND JR  31/01/46  M  LAWRENCE      LAWRENCE LIND JR  True
(39, 6)

## Final result files generated are:

## "using token sort by only full name.csv" 39 rows
## "using token sort by unique gender.csv" 39 rows
## "using token sort by unique dob.csv" 39 rows

## "using token sort by unique dob and gender.csv"--> 51 rows